### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mohammed-Emad** [AmalAsaad/Dragon-Arena#85]
Hello good job..
Why didn't you launch it on a platform [netlify.app](https://netlify.app)?

**Comment by AmalAsaad** [comment]
Thanks.
we already did it,
you can check from here 
https://dragon-arena-game.netlify.app/intro.html

**Comment by mohammed-Emad** [comment]
you're welcome
Always for the best 💪👍,I Hope that
